//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MG_Client()
        {
            this.MG_OTK = new HashSet<MG_OTK>();
        }
    
        public int ID { get; set; }
        public string NameProduct { get; set; }
        public string NameClient { get; set; }
        public string SN { get; set; }
        public string DefectName { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> UserID { get; set; }
        public string NumDoc { get; set; }
        public Nullable<System.DateTime> DateComing { get; set; }
        public string StockNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_OTK> MG_OTK { get; set; }
    }
}
